### ISSUE TITLE
[BACKEND] 13. Probar el login con JWS

### ISSUE THREAD

**Issue by J3susGB** [J3susGB/CA-Sevilla_administration#17]
# 🎯 OBJETIVO

Comprobar que todo lo realizado anteriormente de la configuración de JWT funciona, ahora que ya tenemos  creado nuestro primer usuario

**Comment by J3susGB** [comment]
# 1️⃣ Añadir la ruta al archivo routes.yml

```
controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

login:
    path: /api/login
```

![Image](https://github.com/user-attachments/assets/daaf1055-af72-42f2-8f3c-c5b4620f0886)

---

# 2️⃣ Probarlo en Postman
