### ISSUE TITLE
[FRONTEND] 19: Hablitar modal para añadir usuarios

### ISSUE THREAD

**Issue by J3susGB** [J3susGB/CA-Sevilla_administration#25]

**Comment by J3susGB** [comment]
# Documentación de la Implementación del Modal de Usuarios

Este documento describe los pasos realizados para añadir e integrar un modal de creación y carga masiva de usuarios en el proyecto Angular con TailwindCSS, desde la instalación de la librería de Angular Material hasta los ajustes finales de estilos.

## 1. Instalación de Angular Material y CDK

```bash
# Dentro del contenedor o en local, instalar Angular Material, CDK y Animations
npm install @angular/material @angular/cdk @angular/animations
```

## 2. Configuración del Angular Module

- No se utiliza `AppModule` tradicional, se trabaja con `bootstrapApplication` y configuración en `app.config.ts`.
- Se importan los módulos necesarios en los componentes standalone:
  - `MatDialogModule`, `MatTabsModule`, `MatFormFieldModule`, `MatInputModule`, `MatSelectModule`, `MatButtonModule`
  - `OverlayModule` para asegurar que el `<mat-select>` flote correctamente.

## 3. Generación del Componente Modal

```bash
# Comando Angular CLI (en caso de usar CLI tradicional)
ng generate component dashboard-admin/users/user-modal --standalone
```

Se crea:
- `user-modal.component.ts` (lógica y Reactive Forms)
- `user-modal.component.html` (template con dos pestañas)
- `user-modal.component.css` (estilos específicos si se usan)

## 4. Apertura del Modal desde UsersListComponent

En `src/app/dashboard-admin/users/users-list.component.ts`:

```ts
addUser(): void {
  this.dialog.open(UserModalComponent, {
    width: '500px',
    panelClass: 'user-modal-dialog'
  }).afterClosed().subscribe(created => {
    if (created) this.load();
  });
}
```

- `panelClass: 'user-modal-dialog'` identifica el overlay para overrides CSS.

## 5. Estructura del Template del Modal

En `user-modal.component.html` se definen dos pestañas:
- **Individual**: formulario reactivo con campos `username`, `email`, `roles`.
- **Carga masiva**: input de fichero y botón de subida.

Ejemplo de `<mat-select>` para roles:

```html
<mat-form-field appearance="fill" class="w-full mb-4">
  <mat-label>Roles</mat-label>
  <mat-select formControlName="roles" multiple panelClass="user-modal-select-panel">
    <mat-option *ngFor="let r of allRoles" [value]="r">{{ r }}</mat-option>
  </mat-select>
</mat-form-field>
```

## 6. Estilos Globales (src/styles.css)

Se utiliza TailwindCSS con capas `@layer utilities` y `@layer components`. Se incluyen overrides globales al final, fuera de `@layer`, para forzar estilos de hover y select panel.

### Ejemplo de override para panel del select:

```css
/* Panel flotante del mat-select */
.cdk-overlay-container .user-modal-select-panel {
  max-height: 12rem !important;
  overflow-y: auto !important;
  min-width: 12rem !important;
  box-shadow: 0 5px 15px rgba(0, 0, 0, 0.2) !important;
  z-index: 10001 !important;
}
```

### Overrides de Hover para botones:

```css
/* Hover “Cancelar” */
.cdk-overlay-pane.user-modal-dialog button[mat-button]:hover {
  color: #FDE68A !important;
}

/* Hover “Crear” */
.cdk-overlay-pane.user-modal-dialog button[mat-flat-button]:hover {
  background-color: #1E40AF !important;
  color: #FFFFFF !important;
}
```

## 7. Ajustes de Redondeo y Layout

- Se aplica `rounded-2xl` a `.mat-mdc-dialog-container` y `rounded-t-2xl` a `.mat-mdc-dialog-title`.
- Se utiliza `flex flex-col h-full` y `mt-auto` en `mat-dialog-actions` para anclar botones al fondo.

## 8. Resumen

Con estos pasos, se integra un modal completo, responsive y estilizado con Tailwind que permite:
- Crear usuarios individualmente.
- Cargar usuarios mediante un fichero Excel.
- Mantener la consistencia de estilos en ambas pestañas.

---
