### ISSUE TITLE
[FRONTEND] 29: Implementar dialogo de eliminación en eliminar usuario y arbitro (Angular Material)

### ISSUE THREAD

**Issue by J3susGB** [J3susGB/CA-Sevilla_administration#36]

**Comment by J3susGB** [comment]
# Paso 1: Preparar el componente de confirmación

1. Creo un componente standalone `ConfirmDialogComponent` en `src/app/shared/components/confirm-dialog/confirm-dialog.component.ts`:
   ```bash
   ng generate component shared/confirm-dialog \
     --standalone \
     --imports="@angular/material/dialog","@angular/material/button"
   ```
2. Defino la interfaz `ConfirmDialogData` y la plantilla en `confirm-dialog.component.ts` y `confirm-dialog.component.html`:
   - **confirm-dialog.component.ts**:
     ```ts
     import { Component, Inject } from '@angular/core';
     import {
       MatDialogRef,
       MAT_DIALOG_DATA,
       MatDialogModule
     } from '@angular/material/dialog';
     import { MatButtonModule } from '@angular/material/button';

     export interface ConfirmDialogData {
       title: string;
       message: string;
       confirmText?: string;
       cancelText?: string;
     }

     @Component({
       selector: 'app-confirm-dialog',
       standalone: true,
       imports: [MatDialogModule, MatButtonModule],
       templateUrl: './confirm-dialog.component.html'
     })
     export class ConfirmDialogComponent {
       constructor(
         private dialogRef: MatDialogRef<ConfirmDialogComponent>,
         @Inject(MAT_DIALOG_DATA) public data: ConfirmDialogData
       ) {}

       onConfirm() {
         this.dialogRef.close(true);
       }
       onCancel() {
         this.dialogRef.close(false);
       }
     }
     ```
   - **confirm-dialog.component.html**:
     ```html
     <h2 mat-dialog-title class="text-xl font-semibold text-[#00695c] mb-2">
       {{ data.title }}
     </h2>
     <mat-dialog-content class="text-sm text-gray-700">
       {{ data.message }}
     </mat-dialog-content>
     <mat-dialog-actions align="end" class="mt-4 space-x-2">
       <button mat-button (click)="onCancel()" class="px-4 py-2 rounded hover:bg-gray-100">
         {{ data.cancelText || 'Cancelar' }}
       </button>
       <button mat-flat-button color="warn" (click)="onConfirm()"
               class="px-4 py-2 rounded bg-red-600 hover:bg-red-700 text-white">
         {{ data.confirmText || 'Eliminar' }}
       </button>
     </mat-dialog-actions>
     ```

---

# Paso 2: Importar y añadir el diálogo en mis componentes

En los componentes `UsersListComponent` y `ArbitrosListComponent` añado las importaciones:

```ts
import {
  ConfirmDialogComponent,
  ConfirmDialogData
} from '../../shared/components/confirm-dialog/confirm-dialog.component';
```

Y en el decorador `@Component`, dentro de `imports`:

```ts
imports: [
  // ...
  MatDialogModule,
  MatButtonModule,
  // ...
  ConfirmDialogComponent
],
```

---

# Paso 3: Modificar `deleteUser`

En `users-list.component.ts` reemplazo `confirm()` por el diálogo:

```ts
deleteUser(u: User): void {
  const data: ConfirmDialogData = {
    title: `Eliminar a ${u.username}?`,
    message: '¡Esta acción no se puede deshacer!',
    confirmText: 'Eliminar',
    cancelText: 'Cancelar'
  };

  this.dialog.open(ConfirmDialogComponent, {
    data,
    panelClass: 'confirm-dialog-panel',
    backdropClass: 'confirm-dialog-backdrop'
  })
  .afterClosed()
  .subscribe(confirmed => {
    if (!confirmed) return;
    this.userService.delete(u.id!).subscribe({
      next: () => {
        this.load();
        this.toastService.show('Usuario eliminado con éxito 🗑️', 'error');
      },
      error: () => {
        this.toastService.show('Error al eliminar usuario ❌', 'error');
      }
    });
  });
}
```

---

## Paso 4: Modificar `deleteArbitro`

En `arbitros-list.component.ts` aplico el mismo patrón:

```ts
deleteArbitro(a: Arbitro): void {
  const surnames = [a.first_surname, a.second_surname]
    .filter(x => !!x)
    .join(' ');

  const data: ConfirmDialogData = {
    title: `Eliminar a ${surnames}, ${a.name}?`,
    message: '¡Esta acción no se puede deshacer!',
    confirmText: 'Eliminar',
    cancelText: 'Cancelar'
  };

  this.dialog.open(ConfirmDialogComponent, {
    data,
    panelClass: 'confirm-dialog-panel',
    backdropClass: 'confirm-dialog-backdrop'
  })
  .afterClosed()
  .subscribe(confirmed => {
    if (!confirmed) return;
    this.arbSvc.delete(a.id).subscribe({
      next: () => {
        this.load();
        this.toastService.show('Árbitro eliminado con éxito 🗑️', 'error');
      },
      error: () => {
        this.toastService.show('Error al eliminar árbitro ❌', 'error');
      }
    });
  });
}
```

---

## Paso 5: Añadir estilos globales

En `styles.css` o dentro de tu `@layer components`:

```css
/*dialogo de eliminar*/

/* oscurece MUCHO TODO EL FONDO detrás del diálogo */
.cdk-overlay-backdrop.confirm-dialog-backdrop {
  background-color: rgba(0, 0, 0, 0.7) !important;
}

.cdk-overlay-pane.confirm-dialog-panel .mat-mdc-dialog-surface {
  background: #ffffff;
  border-radius: 1rem;
  box-shadow: 0 0px 55px rgba(0,0,0,0.1);
  padding: 1.5rem;
  max-width: 28rem; /* 448px */
  margin: 0 auto;
}

.cdk-overlay-pane.confirm-dialog-panel .mat-mdc-dialog-title {
  font-size: 1.25rem;
  font-weight: 600;
  color: #3B3B3B;
  margin-bottom: 0.5rem;
  text-align: center;
}

.cdk-overlay-pane.confirm-dialog-panel .mat-mdc-dialog-content {
  font-size: 0.875rem;
  color: #374151;
  text-align: center;
}

.cdk-overlay-pane.confirm-dialog-panel .mat-mdc-dialog-actions {
  margin-top: 1rem;
  display: flex;
  justify-content: flex-end;
  gap: 0.5rem;
}

.cdk-overlay-pane.confirm-dialog-panel button[mat-button],
.cdk-overlay-pane.confirm-dialog-panel button[mat-flat-button] {
  padding: 0.5rem 1rem;
  border-radius: 0.375rem;
  transition: background-color 0.2s ease, color 0.2s ease;
}

.cdk-overlay-pane.confirm-dialog-panel button[mat-button]:hover {
  color: #ca8a04;
}

.cdk-overlay-pane.confirm-dialog-panel button[mat-flat-button] {
  background-color: #dc2626;
  color: #fff;
}

.cdk-overlay-pane.confirm-dialog-panel button[mat-flat-button]:hover {
  background-color: #b91c1c;
}
```

---
